In [ ]:
16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
array = np.ones((3, 3))

# Add a border of 0s around the existing array
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(array_with_border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [5]:
print("0 * np.nan:",)               
print("np.nan == np.nan:",)            
print("np.inf > np.nan:",)             
print("np.nan - np.nan:",)             
print("np.nan in set([np.nan]):",)     
print("0.3 == 3 * 0.1:",)  

0 * np.nan:
np.nan == np.nan:
np.inf > np.nan:
np.nan - np.nan:
np.nan in set([np.nan]):
0.3 == 3 * 0.1:


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [6]:
values = np.array([1, 2, 3, 4])

# Create a 5x5 matrix with these values just below the main diagonal (k=-1)
matrix = np.diag(values, k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [7]:
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?


In [8]:
shape = (6, 7, 8)

# Calculate the index (x, y, z) of the 100th element
index = np.unravel_index(100, shape)

print(index)

(np.int64(1), np.int64(5), np.int64(4))


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [9]:
pattern = np.array([[1, 0],
                    [0, 1]])

# Tile the pattern to create an 8x8 matrix
checkerboard = np.tile(pattern, (4, 4))

print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix (★☆☆)


In [10]:
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("Original Matrix:\n", random_matrix)
print("Normalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[8.52426179e-01 9.30561874e-01 9.14402085e-02 7.06179457e-01
  8.26221390e-01]
 [7.35340675e-01 4.53270641e-01 2.91997380e-01 1.45990625e-01
  3.53461618e-01]
 [7.17976634e-01 5.76510600e-01 4.08161358e-01 5.95142915e-01
  6.19293771e-01]
 [8.19666861e-01 9.43655638e-01 9.02427575e-01 9.90457619e-01
  7.85154799e-01]
 [7.73112998e-01 6.96485265e-02 8.56155401e-01 6.93277062e-04
  1.51045795e-01]]
Normalized Matrix:
 [[0.86054111 0.93948484 0.09168539 0.71278197 0.83406532]
 [0.74224476 0.4572577  0.29431663 0.14679994 0.3564165 ]
 [0.72470115 0.58177214 0.41168192 0.60059714 0.62499776]
 [0.82744301 0.95271402 0.91105959 1.         0.79257404]
 [0.78040771 0.06966835 0.86430889 0.         0.15190739]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [11]:
# Define the custom dtype for RGBA color
color_dtype = np.dtype([
    ('r', np.uint8),  # Red component
    ('g', np.uint8),  # Green component
    ('b', np.uint8),  # Blue component
    ('a', np.uint8)   # Alpha component
])

# Example of using this dtype to create an array of colors
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

print(colors)
print(colors['r'])  # Accessing the red component
print(colors['g'])  # Accessing the green component
print(colors['b'])  # Accessing the blue component
print(colors['a'])  # Accessing the alpha component

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]
[255   0   0]
[  0 255   0]
[  0   0 255]
[255 255 255]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [12]:
matrix1 = np.random.rand(5, 3)

matrix2 = np.random.rand(3, 2)

result = np.dot(matrix1, matrix2)


Matrix 1:
 [[0.54283397 0.45274273 0.77101276]
 [0.57327423 0.19412349 0.60982966]
 [0.26858285 0.06831172 0.07581066]
 [0.84110375 0.04516341 0.60931202]
 [0.7968355  0.28869644 0.12918377]]
Matrix 2:
 [[0.12238932 0.49428017]
 [0.23654198 0.10938961]
 [0.7169625  0.41305692]]
Result of multiplication:
 [[0.72631698 0.63630957]
 [0.553306   0.55648754]
 [0.10338366 0.17154188]
 [0.55047903 0.67236186]
 [0.2584329  0.47880062]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [13]:
# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate all elements which are between 3 and 8
array[(array > 3) & (array < 8)] *= -1

print(array)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script? (★☆☆)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [14]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [18]:
result1 = np.array(0) / np.array(0)
print(result1)

nan


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_12704\403653203.py:1: RuntimeWarning: invalid value encountered in divide
  result1 = np.array(0) / np.array(0)


In [19]:
result2 = np.array(0) // np.array(0)
print(result2)

0


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_12704\342119538.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  result2 = np.array(0) // np.array(0)


29. How to round away from zero a float array ? (★☆☆)


In [ ]:
# Round away from zero
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
float_array=4                            

print("4:", float_array)
print("5:", rounded_array)

30. How to find common values between two arrays? (★☆☆)


In [22]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Common values: [4 5]
