In [ ]:
31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [2]:
import numpy as np

In [4]:
import warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)


AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [5]:
result_1 = np.sqrt(-1)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_7632\2703645769.py:1: RuntimeWarning: invalid value encountered in sqrt
  result_1 = np.sqrt(-1)


33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


In [5]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(days=1)

tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-07-08
Today: 2024-07-09
Tomorrow: 2024-07-10


34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [6]:
import pandas as pd

july_2016 = pd.date_range(start="2016-07-01", end="2016-07-31")

print(july_2016)


DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [1]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A *= -0.5
A += B
A *= B

print(A)


UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [8]:
random_array = np.random.random(10) * 100

int_part_floor = np.floor(random_array)

int_part_trunc = np.trunc(random_array)

int_part_cast = random_array.astype(int)

int_part_astype = random_array.astype(int)

print("Original array:", random_array)
print("Integer part using floor:", int_part_floor)
print("Integer part using trunc:", int_part_trunc)
print("Integer part using type casting:", int_part_cast)
print("Integer part using astype:", int_part_astype)

Original array: [13.89147394 37.13303873 96.37705409 28.61841084 60.94479607 70.9401511
 91.14924281 28.49585397 17.4772469  82.81973938]
Integer part using floor: [13. 37. 96. 28. 60. 70. 91. 28. 17. 82.]
Integer part using trunc: [13. 37. 96. 28. 60. 70. 91. 28. 17. 82.]
Integer part using type casting: [13 37 96 28 60 70 91 28 17 82]
Integer part using astype: [13 37 96 28 60 70 91 28 17 82]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [9]:
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [10]:
def generate_integers():
    for i in range(10):
        return i

integer_list = list(generate_integers())

integer_array = np.array(integer_list)

print(integer_array)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [11]:
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it (★★☆)


In [12]:
random_vector = np.random.random(10)

sorted_vector = np.sort(random_vector)

print("Random vector:", random_vector)
print("Sorted vector:", sorted_vector)

Random vector: [0.14548474 0.1758136  0.49133989 0.10633022 0.11087649 0.50002147
 0.38420092 0.22861016 0.29976049 0.17502004]
Sorted vector: [0.10633022 0.11087649 0.14548474 0.17502004 0.1758136  0.22861016
 0.29976049 0.38420092 0.49133989 0.50002147]


41. How to sum a small array faster than np.sum? (★★☆)


In [13]:
small_array = np.array([1, 2, 3, 4, 5])

np_sum_result = np.sum(small_array)

built_in_sum_result = sum(small_array)

print("Sum using np.sum:", np_sum_result)
print("Sum using built-in sum:", built_in_sum_result)

Sum using np.sum: 15
Sum using built-in sum: 15


42. Consider two random array A and B, check if they are equal (★★☆)


In [14]:
A = np.random.random(10)
B = np.random.random(10)

are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are they equal?", are_equal)

Array A: [0.95796081 0.2208615  0.83864697 0.82195531 0.82827502 0.21460239
 0.40210588 0.37200373 0.53556996 0.67307387]
Array B: [0.76049161 0.32937358 0.51161298 0.17396919 0.41641225 0.70245125
 0.60694837 0.96397247 0.52100695 0.53902534]
Are they equal? False


43. Make an array immutable (read-only) (★★☆)


In [1]:
array = np.random.random(10)


NameError: name 'np' is not defined

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [2]:
import numpy as np

cartesian_coords = np.random.random((10, 2))



45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [17]:
import numpy as np

random_vector = np.random.random(10)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Random vector with maximum value replaced by 0:\n", random_vector)


Random vector with maximum value replaced by 0:
 [0.42029889 0.10712434 0.38031905 0.40697466 0.25204949 0.15955603
 0.8260297  0.72952064 0.4250219  0.        ]
