In [1]:
import numpy

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)


In [4]:
print("NumPy Version:", np.__version__)


NumPy Version: 2.0.0


3. Create a null vector of size 10 (★☆☆)


In [5]:
null_vector = np.zeros(10)

print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)


In [6]:
array = np.array([1, 2, 3, 4, 5])

# Find the memory size of the array
memory_size = array.nbytes

print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 40 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [8]:
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [9]:
null_vector = np.zeros(10)

# Set the fifth value to 1 (index 4, as indexing starts at 0)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [10]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)


In [11]:
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [12]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [13]:
array = np.array([1, 2, 0, 0, 4, 0])

# Find indices of non-zero elements
non_zero_indices = np.nonzero(array)

print(non_zero_indices)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix (★☆☆)


In [14]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)


In [15]:
array_3d = np.random.rand(3, 3, 3)

print(array_3d)

[[[0.86031634 0.30518959 0.65243104]
  [0.10578442 0.52927479 0.80509619]
  [0.45162909 0.62705744 0.61062947]]

 [[0.63482885 0.12085113 0.93011757]
  [0.36632104 0.47872564 0.06060383]
  [0.70204769 0.56276637 0.79102076]]

 [[0.01259446 0.72605831 0.21301292]
  [0.29390559 0.79303037 0.41435804]
  [0.20272169 0.34720642 0.97023263]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [16]:
array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.0017576713599319893
Maximum value: 0.9962711935154293


14. Create a random vector of size 30 and find the mean value (★☆☆)


In [17]:
vector = np.random.rand(30)

# Find the mean value of the vector
mean_value = np.mean(vector)

print("Mean value of the vector:", mean_value)

Mean value of the vector: 0.5106403601141983


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [18]:
n = 4
array = np.ones((n, n))

# Set interior values to 0
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
