In [5]:
import numpy as np

61. Find the nearest value from a given value in an array (★★☆)


In [6]:
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
value = 6.5
nearest_value = find_nearest(array, value)
print(f"The nearest value to {value} is {nearest_value}")

The nearest value to 6.5 is 6


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


In [7]:

array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

result = np.empty((3, 3))

with np.nditer([array1, array2, result], op_flags=['readwrite'], flags=['external_loop'], order='C') as it:
    for x, y, z in it:
        z[...] = x + y

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Sum:")
print(result)


ValueError: output operand requires a reduction along dimension 0, but the reduction is not enabled. The dimension size of 1 does not match the expected output shape.

63. Create an array class that has a name attribute (★★☆)


In [8]:

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "")

data = np.array([1, 2, 3, 4, 5])
named_array = NamedArray(data, name="MyArray")

print(named_array)
print(f"Array name: {named_array.name}")


[1 2 3 4 5]
Array name: MyArray


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


In [9]:

vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

indices = np.array([1, 3, 3, 5, 7, 7, 7])
np.add.at(vector, indices, 1)

print("Updated vector:")
print(vector)


Updated vector:
[ 0  2  2  5  4  6  6 10  8  9]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [10]:

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

I = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3])

F = np.zeros(5)

np.add.at(F, I, X)

print("Accumulated array F:")
print(F)



Accumulated array F:
[ 7.  9. 11. 13.  5.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


In [13]:

image = np.array([[[0, 0, 0], [255, 255, 255], [255, 0, 0]],
                  [[0, 255, 0], [0, 0, 255], [255, 255, 255]],
                  [[0, 0, 0], [255, 0, 0], [0, 255, 0]]], dtype=np.uint8)

reshaped_image = image.reshape(-1, 3)

unique_colors = np.unique(reshaped_image, axis=0)

num_unique_colors = unique_colors.shape[0]

print("Number of unique colors:", num_unique_colors)


Number of unique colors: 5


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


In [2]:
import numpy as np

In [14]:

array_4d = np.random.rand(3, 4, 5, 6)

sum_last_two_axes = np.sum(array_4d, axis=(-2, -1))

print("Original array shape:", array_4d.shape)
print("Sum over the last two axes shape:", sum_last_two_axes.shape)
print("Sum over the last two axes:")
print(sum_last_two_axes)


Original array shape: (3, 4, 5, 6)
Sum over the last two axes shape: (3, 4)
Sum over the last two axes:
[[14.69996602 11.25833888 14.1894675  15.11544395]
 [15.49625992 16.24598735 14.73700702 16.54771139]
 [16.18024126 15.28560955 15.14051119 15.14934513]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


In [15]:
import numpy as np
import pandas as pd

D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 1, 0, 1, 0, 1, 2, 2, 2, 2])

df = pd.DataFrame({'D': D, 'S': S})

means = df.groupby('S')['D'].mean()

print("Means of subsets of D based on S:")
print(means)


Means of subsets of D based on S:
S
0    3.0
1    4.0
2    8.5
Name: D, dtype: float64


69. How to get the diagonal of a dot product? (★★★)


In [3]:

A = np.random.rand(4, 3)
B = np.random.rand(3, 4)

diag_dot_product = np.einsum('ij,ji->i', A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Diagonal of the dot product of A and B:")
print(diag_dot_product)


Matrix A:
[[0.90302276 0.06750501 0.84878445]
 [0.25647035 0.58727054 0.79670892]
 [0.4486345  0.71963045 0.41622344]
 [0.60100598 0.70093697 0.09049253]]
Matrix B:
[[0.05757203 0.0557553  0.93257973 0.98517609]
 [0.17523761 0.82646156 0.06481024 0.26023144]
 [0.38359515 0.596323   0.92229048 0.75767807]]
Diagonal of the dot product of A and B:
[0.38940787 0.97475197 0.84890578 0.84306676]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [4]:
import numpy as np

original_vector = np.array([1, 2, 3, 4, 5])

num_zeros = 3

new_size = len(original_vector) * (num_zeros + 1) - num_zeros

new_vector = np.zeros(new_size, dtype=original_vector.dtype)

new_vector[::num_zeros + 1] = original_vector

print("Original vector:")
print(original_vector)
print("New vector with interleaved zeros:")
print(new_vector)


Original vector:
[1 2 3 4 5]
New vector with interleaved zeros:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [5]:
import numpy as np

array_5x5x3 = np.random.rand(5, 5, 3)
array_5x5 = np.random.rand(5, 5)
expanded_array_5x5 = array_5x5[:, :, np.newaxis]

result = array_5x5x3 * expanded_array_5x5

print("Original (5,5,3) array:")
print(array_5x5x3)
print("Original (5,5) array:")
print(array_5x5)
print("Expanded (5,5,1) array:")
print(expanded_array_5x5)
print("Result of element-wise multiplication:")
print(result)


Original (5,5,3) array:
[[[0.8553311  0.67119233 0.60986953]
  [0.38557824 0.44117652 0.47063109]
  [0.81566014 0.18487116 0.68028939]
  [0.77331741 0.55614809 0.02977178]
  [0.54481049 0.01774643 0.58112481]]

 [[0.47179067 0.6318478  0.95301546]
  [0.40874465 0.83300703 0.43961727]
  [0.16049539 0.43231192 0.0878583 ]
  [0.27995391 0.11238851 0.32071361]
  [0.65721119 0.1970845  0.88257644]]

 [[0.81551674 0.46937301 0.7074101 ]
  [0.48441013 0.33498994 0.17040672]
  [0.41322581 0.72979252 0.11309238]
  [0.22381288 0.15176871 0.34354563]
  [0.82113841 0.50492475 0.28012618]]

 [[0.3419896  0.0172784  0.77177336]
  [0.00496804 0.62879885 0.65531606]
  [0.13937208 0.17425207 0.30612408]
  [0.19739438 0.56485495 0.14390563]
  [0.17947008 0.44033053 0.32997502]]

 [[0.40570208 0.5182764  0.39895632]
  [0.95571256 0.82788477 0.87716902]
  [0.78834394 0.73377997 0.08946819]
  [0.035675   0.37287813 0.03909862]
  [0.95923795 0.39718414 0.37221857]]]
Original (5,5) array:
[[0.293079   0.2340

72. How to swap two rows of an array? (★★★)


In [6]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row1, row2 = 0, 2

array[[row1, row2]] = array[[row2, row1]]

print("Array after swapping rows:")
print(array)


Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


In [7]:
import numpy as np

triangles = np.array([
    [0, 1, 2],
    [0, 2, 3],
    [0, 3, 4],
    [0, 4, 5],
    [0, 5, 6],
    [0, 6, 7],
    [0, 7, 8],
    [0, 8, 9],
    [0, 9, 1],
    [1, 2, 3]
])

def extract_unique_edges(triangles):
    edges = set()
    for triangle in triangles:
        
        edges.add(tuple(sorted([triangle[0], triangle[1]])))
        edges.add(tuple(sorted([triangle[1], triangle[2]])))
        edges.add(tuple(sorted([triangle[2], triangle[0]])))
    return edges

unique_edges = extract_unique_edges(triangles)

print("Unique edges:")
for edge in unique_edges:
    print(edge)


Unique edges:
(np.int64(3), np.int64(4))
(np.int64(0), np.int64(2))
(np.int64(8), np.int64(9))
(np.int64(0), np.int64(5))
(np.int64(0), np.int64(8))
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(9))
(np.int64(4), np.int64(5))
(np.int64(5), np.int64(6))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(7))
(np.int64(1), np.int64(2))
(np.int64(0), np.int64(4))
(np.int64(6), np.int64(7))
(np.int64(0), np.int64(3))
(np.int64(0), np.int64(9))
(np.int64(0), np.int64(6))
(np.int64(2), np.int64(3))
(np.int64(7), np.int64(8))


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


In [8]:
import numpy as np

C = np.array([3, 2, 1, 0, 4])

A_list = []

for i, count in enumerate(C):
    A_list.extend([i] * count)

A = np.array(A_list)

print("Array A:")
print(A)

print("Bincount of A:")
print(np.bincount(A))
print("C:")
print(C)


Array A:
[0 0 0 1 1 2 4 4 4 4]
Bincount of A:
[3 2 1 0 4]
C:
[3 2 1 0 4]


75. How to compute averages using a sliding window over an array? (★★★)


In [9]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

window_size = 3

window = np.ones(window_size) / window_size
averages = np.convolve(array, window, mode='valid')

print("Input array:")
print(array)
print(f"Sliding window averages (window size = {window_size}):")
print(averages)


Input array:
[ 1  2  3  4  5  6  7  8  9 10]
Sliding window averages (window size = 3):
[2. 3. 4. 5. 6. 7. 8. 9.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


In [10]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

window_size = 3
rows = []
for i in range(len(Z) - window_size + 1):
    row = Z[i:i + window_size]
    rows.append(row)

result = np.array(rows)

print("One-dimensional array Z:")
print(Z)
print("Two-dimensional array with shifted rows:")
print(result)


One-dimensional array Z:
[1 2 3 4 5 6 7 8 9]
Two-dimensional array with shifted rows:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


In [11]:
import numpy as np

bool_array = np.array([True, False, True, False, True])

bool_array = ~bool_array

print("Negated boolean array:")
print(bool_array)


Negated boolean array:
[False  True False  True False]


In [12]:
import numpy as np

float_array = np.array([1.0, -2.5, 3.3, -4.8, 5.9])

float_array *= -1

print("Float array with signs changed:")
print(float_array)


Float array with signs changed:
[-1.   2.5 -3.3  4.8 -5.9]


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


In [13]:
import numpy as np

P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
p = np.array([1, 2])

def point_to_line_distance(P0, P1, p):

    line_vec = P1 - P0

    p_vec = p - P0

    cross_prod = line_vec[:, 0] * p_vec[:, 1] - line_vec[:, 1] * p_vec[:, 0]

    dist = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)
    return dist

distances = point_to_line_distance(P0, P1, p)

print("Distances from point p to each line (P0[i], P1[i]):")
print(distances)


Distances from point p to each line (P0[i], P1[i]):
[2. 1. 0.]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


In [14]:
import numpy as np

P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[1, 2], [2, 3], [3, 4]])

def point_to_lines_distances(P0, P1, P):

    line_vec = P1 - P0

    P0_exp = P0[:, np.newaxis, :]  
    P_exp = P[np.newaxis, :, :]    
    p_vec = P_exp - P0_exp        
    cross_prod = line_vec[:, np.newaxis, 0] * p_vec[:, :, 1] - line_vec[:, np.newaxis, 1] * p_vec[:, :, 0]
    
    dist = np.abs(cross_prod) / np.linalg.norm(line_vec, axis=1)[:, np.newaxis]
    return dist

distances = point_to_lines_distances(P0, P1, P)

print("Distances from each point P[j] to each line (P0[i], P1[i]):")
print(distances)


Distances from each point P[j] to each line (P0[i], P1[i]):
[[2. 3. 4.]
 [1. 2. 3.]
 [0. 1. 2.]]


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [16]:
import numpy as np

# array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

window_size = 4
R = np.array([Z[i:i+window_size] for i in range(len(Z) - window_size + 1)])

print("Array Z:")
print(Z)
print("\nGenerated array R:")
print(R)


Array Z:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Generated array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★)


In [17]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)
print(f"\nRank of the matrix: {rank}")


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of the matrix: 2


83. How to find the most frequent value in an array?


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 2, 2, 3, 4, 5, 2, 2])

most_frequent_value = np.bincount(arr).argmax()

print("Array:")
print(arr)
print(f"\nThe most frequent value is: {most_frequent_value}")


Array:
[1 2 3 2 2 3 4 5 2 2]

The most frequent value is: 2


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [19]:
import numpy as np

np.random.seed(0)  
matrix = np.random.randint(0, 10, size=(10, 10))

block_size = 3

blocks = []

for i in range(matrix.shape[0] - block_size + 1):
    for j in range(matrix.shape[1] - block_size + 1):
        block = matrix[i:i+block_size, j:j+block_size]
        blocks.append(block)

blocks = np.array(blocks)

print("Original Matrix:")
print(matrix)
print("\nExtracted 3x3 Blocks:")
for idx, block in enumerate(blocks):
    print(f"Block {idx}:\n{block}\n")


Original Matrix:
[[5 0 3 3 7 9 3 5 2 4]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7 2 0]
 [0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]]

Extracted 3x3 Blocks:
Block 0:
[[5 0 3]
 [7 6 8]
 [5 9 8]]

Block 1:
[[0 3 3]
 [6 8 8]
 [9 8 9]]

Block 2:
[[3 3 7]
 [8 8 1]
 [8 9 4]]

Block 3:
[[3 7 9]
 [8 1 6]
 [9 4 3]]

Block 4:
[[7 9 3]
 [1 6 7]
 [4 3 0]]

Block 5:
[[9 3 5]
 [6 7 7]
 [3 0 3]]

Block 6:
[[3 5 2]
 [7 7 8]
 [0 3 5]]

Block 7:
[[5 2 4]
 [7 8 1]
 [3 5 0]]

Block 8:
[[7 6 8]
 [5 9 8]
 [2 3 8]]

Block 9:
[[6 8 8]
 [9 8 9]
 [3 8 1]]

Block 10:
[[8 8 1]
 [8 9 4]
 [8 1 3]]

Block 11:
[[8 1 6]
 [9 4 3]
 [1 3 3]]

Block 12:
[[1 6 7]
 [4 3 0]
 [3 3 3]]

Block 13:
[[6 7 7]
 [3 0 3]
 [3 3 7]]

Block 14:
[[7 7 8]
 [0 3 5]
 [3 7 0]]

Block 15:
[[7 8 1]
 [3 5 0]
 [7 0 1]]

Block 16:
[[5 9 8]
 [2 3 8]
 [9 9 0]]

Block 17:
[[9 8 9]
 [3 8 1]
 [9 0 4]]

Block 18:
[[8 9 4]
 [8 1 3]
 [0 4 7]]

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [20]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
    
        obj = np.asarray(input_array).view(cls)
        return obj

    def __setitem__(self, index, value):
        super().__setitem__(index, value)
    
        if index[0] != index[1]:
            super().__setitem__((index[1], index[0]), value)

Z = SymmetricArray(np.zeros((5, 5)))
Z[1, 2] = 10
Z[3, 4] = 20

print("Symmetric Array Z:")
print(Z)


Symmetric Array Z:
[[ 0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0. 20.]
 [ 0.  0.  0. 20.  0.]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [21]:
import numpy as np

p = 3
n = 4

matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]

sum_matrix_products = sum(np.matmul(matrices[i], vectors[i]) for i in range(p))

print("Matrices:")
for i, matrix in enumerate(matrices):
    print(f"Matrix {i+1}:\n{matrix}")

print("\nVectors:")
for i, vector in enumerate(vectors):
    print(f"Vector {i+1}:\n{vector}")

print("\nSum of Matrix Products:")
print(sum_matrix_products)


Matrices:
Matrix 1:
[[0.971945   0.87819347 0.50962438 0.05571469]
 [0.45115921 0.01998767 0.44171092 0.97958673]
 [0.35944446 0.48089353 0.68866118 0.88047589]
 [0.91823547 0.21682214 0.56518887 0.86510256]]
Matrix 2:
[[0.50896896 0.91672295 0.92115761 0.08311249]
 [0.27771856 0.0093567  0.84234208 0.64717414]
 [0.84138612 0.26473016 0.39782075 0.55282148]
 [0.16494046 0.36980809 0.14644176 0.56961841]]
Matrix 3:
[[0.70373728 0.28847644 0.43328806 0.75610669]
 [0.39609828 0.89603839 0.63892108 0.89155444]
 [0.68005557 0.44919774 0.97857093 0.11620191]
 [0.7670237  0.41182014 0.67543908 0.24979628]]

Vectors:
Vector 1:
[[0.31321833]
 [0.96541622]
 [0.58846509]
 [0.65966841]]
Vector 2:
[[0.53320625]
 [0.23053302]
 [0.39486929]
 [0.61880856]]
Vector 3:
[[0.47486752]
 [0.47013219]
 [0.71607453]
 [0.287991  ]]

Sum of Matrix Products:
[[3.38461302]
 [3.27369732]
 [3.84007489]
 [3.09716525]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


In [22]:
import numpy as np

# Create a random 16x16 array (example)
np.random.seed(0)  # For reproducibility
arr = np.random.randint(0, 10, size=(16, 16))

# Define block size
block_size = 4

# Calculate number of blocks in each dimension
num_blocks = arr.shape[0] // block_size

# Reshape the array to facilitate block summing
reshaped_arr = arr.reshape(num_blocks, block_size, num_blocks, block_size)

# Sum over blocks (axis=(1,3) sums over the block dimensions)
block_sum = reshaped_arr.sum(axis=(1, 3))

print("Original Array:")
print(arr)
print("\nBlock-Sum with Block Size 4x4:")
print(block_sum)


Original Array:
[[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1 9 9 0 4 7 3 2 7]
 [2 0 0 4 5 5 6 8 4 1 4 9 8 1 1 7]
 [9 9 3 6 7 2 0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1 5 9 3 0 5 0]
 [1 2 4 2 0 3 2 0 7 5 9 0 2 7 2 9]
 [2 3 3 2 3 4 1 2 9 1 4 6 8 2 3 0]
 [0 6 0 6 3 3 8 8 8 2 3 2 0 8 8 3]
 [8 2 8 4 3 0 4 3 6 9 8 0 8 5 9 0]
 [9 6 5 3 1 8 0 4 9 6 5 7 8 8 9 2]
 [8 6 6 9 1 6 8 8 3 2 3 6 3 6 5 7]
 [0 8 4 6 5 8 2 3 9 7 5 3 4 5 3 3]
 [7 9 9 9 7 3 2 3 9 7 7 5 1 2 2 8]
 [1 5 8 4 0 2 5 5 0 8 1 1 0 3 8 8]
 [4 4 0 9 3 7 3 2 1 1 2 1 4 2 5 5]]

Block-Sum with Block Size 4x4:
[[55 90 69 69]
 [66 47 78 58]
 [86 68 79 89]
 [87 60 67 63]]


88. How to implement the Game of Life using numpy arrays? (★★★)


89. How to get the n largest values of an array (★★★)


In [23]:
import numpy as np

# Example array
arr = np.array([3, 1, 8, 4, 5, 9, 2, 7, 6])

# Number of largest values to retrieve
n_largest = 3

# Use np.partition to get the indices of the n largest values
indices = np.argpartition(arr, -n_largest)[-n_largest:]

# Sort the n largest values
n_largest_values = arr[indices]

print(f"The {n_largest} largest values are: {n_largest_values}")


The 3 largest values are: [7 8 9]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


In [24]:
from itertools import product

# Example vectors
vec1 = [1, 2, 3]
vec2 = ['a', 'b']
vec3 = [True, False]

# Compute Cartesian product
cartesian_product = list(product(vec1, vec2, vec3))

print("Cartesian Product:")
for combination in cartesian_product:
    print(combination)


Cartesian Product:
(1, 'a', True)
(1, 'a', False)
(1, 'b', True)
(1, 'b', False)
(2, 'a', True)
(2, 'a', False)
(2, 'b', True)
(2, 'b', False)
(3, 'a', True)
(3, 'a', False)
(3, 'b', True)
(3, 'b', False)


In [ ]:
91. How to create a record array from a regular array? (★★★)


In [1]:
import numpy as np

# Regular array
regular_array = np.array([(1, 2.0, 'Hello'), (3, 4.0, 'World')])

# Define dtype for record array
dtype = [('col1', int), ('col2', float), ('col3', 'U10')]  # U10: Unicode string of length 10

# Create record array
record_array = np.rec.array(regular_array, dtype=dtype)

print("Regular Array:")
print(regular_array)
print("\nRecord Array:")
print(record_array)


ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype

92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


In [3]:
import numpy as np

# Create a large vector Z
Z = np.random.rand(1000000)

Z_cubed_vectorized = Z ** 3

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [9]:
import numpy as np

A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

A_sets = [set(row) for row in A]
B_sets = [set(row) for row in B]

result = []
for b_set in B_sets:
    for i, a_set in enumerate(A_sets):
        if b_set.issubset(a_set):
            result.append(A[i])

result = np.array(result)

print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nRows of A that contain elements of each row of B:")
print(result)


Array A:
[[1 4 1]
 [3 2 4]
 [1 2 4]
 [4 0 4]
 [0 3 4]
 [0 1 0]
 [0 3 2]
 [4 0 4]]

Array B:
[[0 3]
 [1 2]]

Rows of A that contain elements of each row of B:
[[0 3 4]
 [0 3 2]
 [1 2 4]]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [10]:
import numpy as np

matrix = np.random.randint(0, 5, (10, 3))


unique_rows = matrix[np.apply_along_axis(lambda x: len(set(x)) == len(x), 1, matrix)]

print("Matrix:")
print(matrix)
print("\nRows with unequal values:")
print(unique_rows)


Matrix:
[[1 2 1]
 [3 4 0]
 [3 4 2]
 [2 1 4]
 [1 1 1]
 [4 0 4]
 [0 3 1]
 [1 0 1]
 [1 1 0]
 [1 2 0]]

Rows with unequal values:
[[3 4 0]
 [3 4 2]
 [2 1 4]
 [0 3 1]
 [1 2 0]]


95. Convert a vector of ints into a matrix binary representation (★★★)


In [11]:
import numpy as np


vector = np.array([3, 7, 15, 8])


def int_to_padded_binary(x, max_len):
    return np.binary_repr(x).zfill(max_len)


max_len = len(np.binary_repr(vector.max()))


binary_matrix = np.array([list(int_to_padded_binary(x, max_len)) for x in vector], dtype=int)

print("Original vector:")
print(vector)
print("\nBinary matrix:")
print(binary_matrix)


Original vector:
[ 3  7 15  8]

Binary matrix:
[[0 0 1 1]
 [0 1 1 1]
 [1 1 1 1]
 [1 0 0 0]]


96. Given a two dimensional array, how to extract unique rows? (★★★)


In [12]:
import numpy as np


array = np.array([[1, 2, 3],
                  [3, 4, 5],
                  [1, 2, 3],
                  [6, 7, 8],
                  [3, 4, 5]])


unique_rows = np.unique(array, axis=0)

print("Original array:")
print(array)
print("\nUnique rows:")
print(unique_rows)


Original array:
[[1 2 3]
 [3 4 5]
 [1 2 3]
 [6 7 8]
 [3 4 5]]

Unique rows:
[[1 2 3]
 [3 4 5]
 [6 7 8]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


In [13]:
import numpy as np

# Example vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])


In [14]:
inner_product = np.einsum('i,i', A, B)
print("Inner product:", inner_product)


Inner product: 32


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


In [16]:
import numpy as np


X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 0, 1, 0])


distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumulative_distances = np.concatenate([[0], np.cumsum(distances)])
num_samples = 10


equidistant_distances = np.linspace(0, cumulative_distances[-1], num_samples)


X_equidistant = np.interp(equidistant_distances, cumulative_distances, X)
Y_equidistant = np.interp(equidistant_distances, cumulative_distances, Y)

print("Original X:", X)
print("Original Y:", Y)
print("Equidistant X:", X_equidistant)
print("Equidistant Y:", Y_equidistant)


Original X: [0 1 2 3 4]
Original Y: [0 1 0 1 0]
Equidistant X: [0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]
Equidistant Y: [0.         0.44444444 0.88888889 0.66666667 0.22222222 0.22222222
 0.66666667 0.88888889 0.44444444 0.        ]


In [ ]:
99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [17]:
import numpy as np

def is_multinomial_row(row, n):
    
    if not np.all(np.equal(np.mod(row, 1), 0)):
        return False
    
    
    if np.sum(row) != n:
        return False
    
    return True

def select_multinomial_rows(X, n):
    
    selected_rows = []
    
    
    for row in X:
        if is_multinomial_row(row, n):
            selected_rows.append(row)
    
    
    selected_rows = np.array(selected_rows)
    
    return selected_rows


X = np.array([[1, 2, 3],
              [2, 2, 2],
              [0, 4, 6],
              [3, 3, 3]])

n = 6


selected_rows = select_multinomial_rows(X, n)

print("Original X:")
print(X)
print("\nSelected rows with sum equal to n ({}):".format(n))
print(selected_rows)


Original X:
[[1 2 3]
 [2 2 2]
 [0 4 6]
 [3 3 3]]

Selected rows with sum equal to n (6):
[[1 2 3]
 [2 2 2]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)


In [20]:
import numpy as np

def bootstrap_confidence_interval(X, num_samples, alpha=0.05):
    
    bootstrap_means = np.empty(num_samples)
    
    
    for i in range(num_samples):
        resampled_X = np.random.choice(X, size=len(X), replace=True)
        bootstrap_means[i] = np.mean(resampled_X)
    
    
    lower_percentile = 100 * alpha / 2
    upper_percentile = 100 * (1 - alpha / 2)
    ci_lower = np.percentile(bootstrap_means, lower_percentile)
    ci_upper = np.percentile(bootstrap_means, upper_percentile)
    
    return ci_lower, ci_upper, bootstrap_means


X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


num_samples = 1000


ci_lower, ci_upper, bootstrap_means = bootstrap_confidence_interval(X, num_samples)

print("Original array X:", X)
print("\nBootstrap 95% confidence interval for the mean:")
print("Lower bound:", ci_lower)
print("Upper bound:", ci_upper)


Original array X: [ 1  2  3  4  5  6  7  8  9 10]

Bootstrap 95% confidence interval for the mean:
Lower bound: 3.7
Upper bound: 7.2
